name: Test Linux
on:
  workflow_call:
    inputs:
      distro-slug:
        type: string
        required: true
        description: The Distribution Slug

      display-name:
        type: string
        required: true
        description: The Display Name For The Job

      instances:
        type: string
        required: true
        description: The Instances To Test

      timeout:
        type: number
        required: false
        default: 20


jobs:
  Test:
    name: ${{ matrix.instance }}
    ## runs-on: ubuntu-20.04
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/saltstack/salt-ci-containers/packaging:ubuntu-22.04

    timeout-minutes: ${{ inputs.timeout }}
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        instance: ${{ fromJSON(inputs.instances) }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Pytest
        run: |
          pip install -U pytest

      - name: Bootstrap Salt
        run: |
          echo "matrix instance ,${{ matrix.instance }},"
          echo "inputs.distro-slug ,${{ inputs.distro-slug }},"
          sh -x ./bootstrap-salt.sh

      - name: Test Bootstrap
        run: |
          pytest --cache-clear -v -s -ra --log-cli-level=debug tests/integration/

      - name: Set Exit Status
        if: always()
        run: |
          mkdir exitstatus
          echo "${{ job.status }}" > exitstatus/${{ github.job }}-${{ matrix.instance }}-${{ inputs.distro-slug }}

      - name: Upload Exit Status
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: exitstatus-${{ github.job }}-${{ matrix.instance }}-${{ inputs.distro-slug }}
          path: exitstatus/
